### ISSUE TITLE
Pls publish on https://hex.pm/

### ISSUE THREAD

**Issue by mindreframer** [houshuang/elixir-prelude#1]
I like this library and it solves some real issues, maybe you should publish it. It's a bit nicer to install packages from hex.pm that pulling directly from github (and you also get usage stats for free ;) !

Cheers!

**Comment by mindreframer** [comment]
Decided to publish it myself, since this issue was ignored... 

https://hex.pm/packages/elixir_prelude 
Cheers, 
Roman

**Comment by houshuang** [comment]
Hi,
very sorry I missed this issue. I'm super stoked that you have improved upon the library and published it to hex.pm. Not doing much Elixir work recently, but once I get back into it, I'll definitively contribute to your version. Great work.

**Comment by mindreframer** [comment]
@houshuang Hey, no probs! I just wanted to use the Map module for deeply nested maps and I liked your implementation. Thanks for providing it as open source! 

Cheers,
Roman
